# JIT GraphRAG Extractor & Gemini Reasoning Agent
import sqlite3
import json
import urllib.request
import urllib.error
import os
from datetime import datetime, timedelta

DB_PATH = "telemetry.db"

def extract_jit_telemetry(lookback_minutes=20):
    """
    Queries SQLite to extract a lightweight service dependency graph 
    and aggregated telemetry from the last 20 minutes.
    """
    if not os.path.exists(DB_PATH):
        return {"error": "Database not initialized. Run the simulator first."}

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    # Calculate time boundary for query (matching local timezone used in simulator)
    time_boundary = (datetime.now() - timedelta(minutes=lookback_minutes)).strftime('%Y-%m-%d %H:%M:%f')

    # 1. Fetch Node Performance Metrics (aggregated by service)
    cursor.execute(
        """
        SELECT 
            service,
            COUNT(*) as request_count,
            AVG(duration_ms) as avg_latency_ms,
            SUM(CASE WHEN status_code >= 500 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) as error_rate_percent
        FROM traces
        WHERE timestamp >= ?
        GROUP BY service
        """,
        (time_boundary,)
    )
    nodes = {}
    for row in cursor.fetchall():
        nodes[row["service"]] = {
            "request_count": row["request_count"],
            "avg_latency_ms": round(row["avg_latency_ms"], 2),
            "error_rate_percent": round(row["error_rate_percent"], 2),
            "anomalous": row["error_rate_percent"] > 5.0 or row["avg_latency_ms"] > 500.0
        }

    # 2. Fetch Call Edges (parent-child spans representing dependency calls)
    cursor.execute(
        """
        SELECT 
            p.service as caller,
            c.service as callee,
            COUNT(*) as call_count,
            AVG(c.duration_ms) as avg_latency_ms,
            SUM(CASE WHEN c.status_code >= 500 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) as error_rate_percent
        FROM traces p
        JOIN traces c ON p.span_id = c.parent_span_id
        WHERE c.timestamp >= ?
        GROUP BY caller, callee
        """,
        (time_boundary,)
    )
    edges = []
    for row in cursor.fetchall():
        edges.append({
            "from": row["caller"],
            "to": row["callee"],
            "call_count": row["call_count"],
            "avg_latency_ms": round(row["avg_latency_ms"], 2),
            "error_rate_percent": round(row["error_rate_percent"], 2)
        })

    # 3. Fetch Error and Critical Logs
    cursor.execute(
        """
        SELECT 
            service,
            level,
            message,
            COUNT(*) as occurrence_count
        FROM logs
        WHERE timestamp >= ? AND level IN ('WARNING', 'ERROR', 'CRITICAL')
        GROUP BY service, level, message
        ORDER BY occurrence_count DESC
        LIMIT 15
        """,
        (time_boundary,)
    )
    logs = []
    for row in cursor.fetchall():
        logs.append({
            "service": row["service"],
            "level": row["level"],
            "message": row["message"],
            "count": row["occurrence_count"]
        })

    # 4. Fetch System Metrics
    cursor.execute(
        """
        SELECT service, metric_name, AVG(value) as avg_value
        FROM metrics
        WHERE timestamp >= ?
        GROUP BY service, metric_name
        """,
        (time_boundary,)
    )
    metrics = []
    for row in cursor.fetchall():
        metrics.append({
            "service": row["service"],
            "metric": row["metric_name"],
            "value": round(row["avg_value"], 2)
        })

    conn.close()

    return {
        "nodes": nodes,
        "edges": edges,
        "logs": logs,
        "metrics": metrics,
        "codebase": get_indexed_codebase_graph(),
        "metadata": {
            "lookback_minutes": lookback_minutes,
            "generated_at": datetime.now().isoformat()
        }
    }

def get_indexed_codebase_graph():
    """
    Queries SQLite codebase_nodes and codebase_edges tables to fetch the permanent
    static codebase structural topology graph generated by indexer.py.
    """
    if not os.path.exists(DB_PATH):
        return {"nodes": [], "edges": []}

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    try:
        # Check if tables exist
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='codebase_nodes'")
        if not cursor.fetchone():
            conn.close()
            return {"nodes": [], "edges": []}

        cursor.execute("SELECT id, label, type, source_file, code_block FROM codebase_nodes")
        nodes = []
        for row in cursor.fetchall():
            nodes.append({
                "id": row["id"],
                "label": row["label"],
                "type": row["type"],
                "source_file": row["source_file"],
                "code_block": row["code_block"]
            })

        cursor.execute("SELECT source, target, relationship FROM codebase_edges")
        edges = []
        for row in cursor.fetchall():
            edges.append({
                "source": row["source"],
                "target": row["target"],
                "relationship": row["relationship"]
            })

        conn.close()
        return {"nodes": nodes, "edges": edges}
    except Exception as e:
        print(f"Error querying codebase graph from sqlite: {e}")
        conn.close()
        return {"nodes": [], "edges": []}

def get_codebase_blueprint():
    """
    Scans the codebase directory recursively, reading microservice codebase files
    and mapping their filenames to their raw file contents for in-context LLM alignment.
    """
    code_dir = os.environ.get("CODEBASE_DIR", "services")
    blueprint = {}
    if not os.path.exists(code_dir):
        return blueprint

    file_count = 0
    for root, _, files in os.walk(code_dir):
        for filename in files:
            if filename.endswith(".py"):
                if file_count >= 100:  # Safety ceiling
                    break
                filepath = os.path.join(root, filename)
                rel_path = os.path.relpath(filepath, code_dir)
                try:
                    with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                        content = f.read()
                        
                        # Hard limit to prevent massive LLMs from choking/timing out
                        if sum(len(c) for c in blueprint.values()) + len(content) > 15000:
                            blueprint[rel_path] = content[:1000] + "\n\n...[TRUNCATED TO PREVENT LLM CONTEXT TIMEOUT]..."
                            break
                            
                        blueprint[rel_path] = content
                    file_count += 1
                except Exception as e:
                    print(f"Error reading codebase file {filepath}: {e}")
    return blueprint

def analyze_incident(graph_data, user_query="Analyze the codebase for bottlenecks.", ollama_url_override="", ollama_model_override="", api_key_override="", api_model_override=""):
    """
    Sends the dynamically constructed graph telemetry AND the local codebase 
    files AND the static codebase graph to a local Ollama model or a remote API (OpenRouter/OpenAI compatible) for reasoning.
    """
    api_key = (api_key_override if api_key_override else os.environ.get("API_KEY", "")).strip()
    api_model = (api_model_override if api_model_override else os.environ.get("API_MODEL", "")).strip()
    ollama_url = (ollama_url_override if ollama_url_override else os.environ.get("OLLAMA_URL", "http://localhost:11434/api/generate")).strip()
    ollama_model = (ollama_model_override if ollama_model_override else os.environ.get("OLLAMA_MODEL", "llama3")).strip()
    
    # Fetch local codebase files and AST Graph
    codebase = get_codebase_blueprint()
    codebase_graph = get_indexed_codebase_graph()

    prompt = f"""
    You are CHRONOS, an elite Autonomous Code-Aware Site Reliability Engineer (SRE).
    You are analyzing a codebase repository mapped into a GraphRAG architecture.
    
    USER QUERY: "{user_query}"
    
    I am providing you with:
    1. The Static Codebase Ontology Graph (AST Extracted classes and methods).
    2. The actual Python codebase file contents.
    3. The dynamic telemetry graph (if live traffic is simulating).
    
    Static Codebase Graph:
    {json.dumps(codebase_graph, indent=2)}

    Codebase Files:
    {json.dumps(codebase, indent=2)}

    Dynamic Telemetry Graph & Logs:
    {json.dumps(graph_data, indent=2)}
    
    Your task is to answer the User Query by causally aligning the data above:
    1. Identify the high-level symptom or architecture answering the query.
    2. Trace the structural edges through the call graph to locate the specific services.
    3. Match the origin service and logs with its corresponding Python code file in the codebase.
    4. Pinpoint the exact function, file, and line numbers relevant to the query.
    5. Draft a corrected, non-blocking code block structured as an executable Git Diff (if applicable).

    Your output MUST be a strict, valid JSON object containing exactly these fields:
    {{
        "incident_summary": "Short 1-sentence summary answering the user query",
        "suspected_root_cause": "Detailed technical explanation based on the code",
        "causal_chain": ["Step-by-step path showing structural execution, e.g. Gateway -> Checkout -> Payment"],
        "confidence_score": 98, // Integer between 0 and 100
        "evidence": ["Bullet list of specific evidence from the codebase AST or telemetry"],
        "remediation_actions": ["Clear, executable commands an engineer can run"],
        "buggy_file": "services/payment_service.py", // The exact path of the relevant file
        "buggy_function": "PaymentService.capture_charge", // Class and method name
        "buggy_code_lines": "def capture_charge(self, amount):...", // Relevant lines from file
        "suggested_git_diff": "--- file.py\\n+++ file.py\\n@@ -1,3 +1,3 @@" // Diff suggesting any improvements
    }}
    
    Ensure your output is ONLY the raw JSON string, starting with {{ and ending with }}. Do not wrap it in markdown codeblocks.
    """

    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Chronos-Agent/1.0",
        "HTTP-Referer": "http://localhost:8000"
    }
    
    if api_key and api_model:
        # Use OpenRouter/OpenAI compatible API
        print(f"Routing to Remote API ({api_model})...")
        url = "https://openrouter.ai/api/v1/chat/completions"
        payload = {
            "model": api_model,
            "messages": [{"role": "user", "content": prompt}]
        }
        
        # Robustly strip redundant Bearer prefix or quotes
        clean_key = api_key
        if clean_key.lower().startswith("bearer "):
            clean_key = clean_key[7:].strip()
        clean_key = clean_key.strip("'\"")
        
        headers["Authorization"] = f"Bearer {clean_key}"
    elif api_key:
        # Fallback for Gemini SDK API directly (if they only gave key)
        print("Routing to Gemini API...")
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"responseMimeType": "application/json"}
        }
    else:
        # Use local Ollama
        print(f"Routing to local Ollama API ({ollama_model})...")
        url = ollama_url
        payload = {
            "model": ollama_model,
            "prompt": prompt,
            "stream": False,
            "format": "json"
        }

    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST"
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as response:
            res_body = json.loads(response.read().decode("utf-8"))
            if api_key and api_model:
                raw_text = res_body["choices"][0]["message"]["content"]
            elif api_key:
                raw_text = res_body["candidates"][0]["content"]["parts"][0]["text"]
            else:
                raw_text = res_body["response"]
                
            import re
            match = re.search(r'\{.*\}', raw_text, re.DOTALL)
            if match:
                return json.loads(match.group(0))
            return json.loads(raw_text.strip())
    except urllib.error.HTTPError as e:
        error_msg = e.read().decode('utf-8')
        print(f"API HTTP Error: {error_msg}")
        return {"error": f"API returned error: {error_msg}"}
    except Exception as e:
        print(f"Error communicating with LLM: {e}")
        return {"error": f"Internal agent reasoning error: {e}"}

if __name__ == "__main__":
    # Test script standalone
    data = extract_jit_telemetry()
    print("--- EXTRACTED JIT GRAPH ---")
    print(json.dumps(data, indent=2))
    
    print("\n--- AGENT REASONING DIAGNOSIS ---")
    analysis = analyze_incident(data, "Find bottlenecks in the code.")
    print(json.dumps(analysis, indent=2))

